### ISSUE TITLE
Update DAP email

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/search-gov-website#158]
https://github.com/GSA/digitalgov.gov/issues/5581

Relates to https://github.com/GSA/search-gov-website/blob/787c2b4eedbe8b402d9a8e0d7c880fa030348d07/_newsletters/2020-12-01-december-2020.md

**Comment by dawnpm** [comment]
Thanks for flagging that, @ryanwoldatwork

**Comment by ryanwoldatwork** [comment]
amazing turnaround. thanks @dawnpm!

**Comment by dawnpm** [comment]
Don't get used to it! :)
